### PR TITLE
Fixed Support Label link on Navbar

### PR DESCRIPTION
**Pull request by PeculiarE**
Fixed Support Label link on Navbar
Updated the file index.html for the proposed changes

Fixes https://github.com/publiclab/community-toolbox/issues/540

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by PeculiarE** [comment]
Hi @TildaDares. I have made another commit to fix the previously failing tests. Could you please approve the workflow once more? Thank you.

**Comment by TildaDares** [comment]
Hi @PeculiarE, can you remove the `package-lock.json` and `dist/community-toolbox.js` files from this PR? Thanks!

**Comment by PeculiarE** [comment]
Hiya @TildaDares....when I made the first commit, the tests on the PR were failing and when I checked the log, the issue was related to failure to install dependencies. I then thought it was because I didn't install the dependencies on my local and just only edited the typo on the` index.html `file.

So I went back to my branch on my PC, did npm install, ran the build just to be sure, and then ran tests. The tests passed but the `package-lock.json` and `dist/community-toolbox.js` files had changes. I thought that committing these changes would fix the failing tests on Github. Turns out I was wrong as the tests are still failing here on Github even though they're passing on my local machine. Do you have any idea why that is?

I have reverted the changes and removed both files from the PR as requested. I'm just puzzled why the tests didn't pass since it was only the `index.html `file I edited.

**Comment by TildaDares** [comment]
Congratulations 🎉🎊

**Comment by PeculiarE** [comment]
Thank you, Tilda! 😃 🥳

**Pull request merged**
