### PR TITLE
Fix The Position Of Fork me Ribbon

### LINKED ISSUE #328: Fork me on github ribbon abruptly moving
### Please describe the problem (or idea)
Fork me on github  abruptly moving when changing the repository from dropdown.
> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?
The tag should not move.

### Please show us where to look

https://code.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system
Brave Browser Version 1.1.21 Chromium: 79.0.3945.79 (Official Build) (64-bit)
Firefox Version 71.0 (64-bit)
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by govindgoel**
Fixes #328 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by govindgoel** [comment]
@publiclab/reviewers  Please review this.
The  changes look like this

**Comment by govindgoel** [comment]
I looked for the changes in file it is properly indented.


Screenshot from 2020-02-08 15-21-46

**Comment by VladimirMikulic** [comment]
@govindgoel  really?
This is your HTML:

```html
<div id='container'>
          <div id='forkMe-ribbon'><a href="https://github.com/publiclab/community-toolbox" >
          <img src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png"alt="Fork me on GitHub"></a>
           </div>
         </div>    
```
This is how it should be:
```html
<div id='container'>
    <div id='forkMe-ribbon'><a href="https://github.com/publiclab/community-toolbox" >
         <img src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png"alt="Fork me on GitHub"></a>
    </div>
</div>    
```

**Comment by govindgoel** [comment]
Done and thanks for helping 
fix

**Comment by govindgoel** [comment]
@Rishabh570  Can you please have a look at  #331 once again

**Pull request merged**
