### PR TITLE
Enhancement in the spinner icon behaviour

### LINKED ISSUE #94: Enhancement in the spinner icon behaviour
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [index.html](https://github.com/publiclab/community-toolbox/blob/main/index.html) and [community-toolbox.js](https://github.com/publiclab/community-toolbox/blob/main/src/community-toolbox.js) in the `community-toolbox` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

**index.html**

```diff
- <div class="well contributors"><i class="fa fa-spinner fa-spin"></i><p class="usernames"></p><hr /><p class="avatars"></p></div>
+ <div class="well contributors"><div id="spinner-icon" style="text-align: center;"><i class="fa fa-spinner fa-spin"></i></div><p class="usernames"></p><hr /><p class="avatars"></p></div>
```

**community-toolbox.js**

At lines [87](https://github.com/publiclab/community-toolbox/blob/main/src/community-toolbox.js#L87), [110](https://github.com/publiclab/community-toolbox/blob/main/src/community-toolbox.js#L110), [128](https://github.com/publiclab/community-toolbox/blob/main/src/community-toolbox.js#L128), [164](https://github.com/publiclab/community-toolbox/blob/main/src/community-toolbox.js#L164) and [180](https://github.com/publiclab/community-toolbox/blob/main/src/community-toolbox.js#L180), add the line shown below,

```diff
- document.getElementById("spinner-icon").style.visibility = "hidden";
+ document.getElementById("spinner-icon").style.display = "none";
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by Buferr**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

Fixes #94

### CODE REVIEW

**Comment by Buferr** [comment]
@Rishabh570 I've just finished. I hope, I didn't mess up anything.

**Comment by Rishabh570** [comment]
Pinging @jywarren

**Comment by jywarren** [comment]
Oh, this looks super! Thank you!!!

**Comment by Buferr** [comment]
@Rishabh570 @jywarren Thanks guys :smile:

**Pull request merged**
