### PR TITLE
Make welcome page text to source from config.json file

### LINKED ISSUE #22: Enable default welcome page text to source from .json file via URL hash
We have some nice text in our example welcome page (which we use for Public Lab projects) -- 

https://publiclab.github.io/community-toolbox/#r=all

But if people want to begin using that just by adding URL hashes for another organization and repository (as in the README), they still see PL text. Let's make it possible to have a .json file that supplies text so people can get this running quickly for themselves!

### PR DESCRIPTION
**Pull request by Rishabh570**
Fixes #22 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Rishabh570** [comment]
@jywarren @publiclab/reviewers I've opened this WIP pull request against issue #22.

This work will make it easy for any org/user to use our project, all they need to do is to edit the `config.json` file in the project root and the welcome page will get customized according to the info provided by them.

Currently working on it, would love to have some feedback :smiley:

**Comment by Rishabh570** [comment]
@jywarren @publiclab/reviewers My work regarding this PR is almost done. Now the main landing page (`index.html`) is flexible to any org/user, they just need to update the `config.json` file in the project root.

Here's a GIF of my changes highlighting the places where data is fed from `config.json` file,

portable

- I've added a dev-package named `http-server` to test/use the `config.json` mechanism locally during development because JSON cannot be fetched using the `file` protocol...Is it okay to leave it as is?

( That yellow color is just for highlighting the places on the page, it is not included in the changes...and all the data is disabled in the GIF just to keep it short, no worries on that part also. )

**Comment by jywarren** [comment]
This is so great!!!!! Is it ready for a review, or still in progress?

**Comment by Rishabh570** [comment]
Yes, it's ready for review now...

**Comment by jywarren** [comment]
Looks great! Want to merge it?

**Comment by Rishabh570** [comment]
Yeah, sure! Thanks :smiley:

**Pull request merged**
