### PR TITLE
Fixes issue #320

### LINKED ISSUE #320: Contributors section's Hyperlinks not working correctly
### Please describe the problem (or idea)

>On clicking the avatar, user is not redirected to corresponding github profile, neither clicking on the username does that.

> What did you expect to see that you didn't?
User should be able to visit the profile of the contributor, by clicking on avatar or username.

### Please show us where to look

ezgif com-video-to-gif (2)

https://code.publiclab.org/ ...

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by DevanshCodes**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #320`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Rishabh570** [comment]
Hi @DevanshCodes, it seems like you're working on your previous (stale) branch as your PR contains changes from other PR also...you can close this and create a fresh branch (on top of main branch) and do the relevant changes there and then open up a new PR. Conflicts might be also coming because of that.

**Comment by somenath1435** [comment]
@DevanshCodes I think, those changes in community-toolbox.js is unnecessary. 
@Rishabh570 your opinion?

**Comment by DevanshCodes** [comment]
> @DevanshCodes I think, those changes in community-toolbox.js is unnecessary.
> @Rishabh570 your opinion?

Can you please tell which changes you are referring too and why they are unncecessary?

**Comment by DevanshCodes** [comment]
> Hi @DevanshCodes, it seems like you're working on your previous (stale) branch as your PR contains changes from other PR also...you can close this and create a fresh branch (on top of main branch) and do the relevant changes there and then open up a new PR. Conflicts might be also coming because of that.

Hey @Rishabh570 I've opened a new PR from new branch, link to that is: https://github.com/publiclab/community-toolbox/pull/325 . Thanks :)

**Pull request closed without merging**
