### PR TITLE
Centering the images by updating demo.css

### LINKED ISSUE #166: Center the images under the "Learn Our Process" section.
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [examples/demo.css](https://github.com/publiclab/community-toolbox/blob/main/examples/demo.css#L37) in the `community-toolbox` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

On **line 37** of `demo.css`,

```diff
- @media (min-width:768px) {
-   .row.section  img {
-     margin-left: 10%;
-   }
- }
```

After removing these lines, save the changes. Then,

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### PR DESCRIPTION
**Pull request by angelisamaria**
Fixes #166

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

Removed @media on line 37
Screen Shot 2019-03-22 at 10 31 27 AM

Screen Shot 2019-03-28 at 11 49 26 AM

### CODE REVIEW

**Comment by angelisamaria** [comment]
@publiclab/reviewers I completed this issue, please let me know if you have any suggestions

**Comment by gauravano** [comment]
Hi @angelisamaria, please mention the issue, you're trying to solve here. Thanks!

**Comment by angelisamaria** [comment]
Removed @media (min-width:768px) on line 37

**Comment by gauravano** [comment]
Actually, you are supposed to mention the issue number in the PR's main comment as given in the instructions - https://github.com/publiclab/community-toolbox/pull/167#issue-262741167. I have done that for you now, but remember to add `fixes #[issue-number]` from next time as it tags issue you are solving and also closes that issue when PR gets merged.

Thanks!

**Comment by gauravano** [comment]
@angelisamaria changes look good, can you attach the screenshot of the updated view? Thanks!

**Comment by angelisamaria** [comment]
Thank you for doing that, I will be sure to add the PR number next time

**Comment by angelisamaria** [comment]
54841941-c9211900-4c8d-11e9-8b49-0791a82d30ff

**Comment by Rishabh570** [comment]
Hey @angelisamaria, sorry I was not clear about the screenshot...I meant the screenshot of the website showing that big three images (under "Learn our Process" section) when the width is greater than `768px`. Thanks for your contribution!!! :+1: :tada:

**Comment by gauravano** [comment]
Dropping screenshot here for completion:

Screenshot from 2019-04-14 20-24-47

Thanks!

Feel free to merge after final review.

**Comment by Rishabh570** [comment]
Merging this :+1:

**Pull request merged**
