### PR TITLE
Add filter for recent contributors' list

### LINKED ISSUE #202: Add filter button for recent contributors' list
Currently, there is no filter option on the recent contributors' list. There can be some options allowing the user to arrange the list according to his needs.

The filter should be based on,
- alphabetical,
- most recent contributors first.

There can be other filters also which can be implemented later...suggestions are welcome :)

### PR DESCRIPTION
**Pull request by Rishabh570**
Fixes #202 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Rishabh570** [comment]
@publiclab/reviewers @jywarren @gauravano Work regarding this PR is almost done, please take a look.

filter

**Comment by Rishabh570** [comment]
@gauravano @publiclab/reviewers This work is complete and updated, please take a look...

**Comment by Rishabh570** [comment]
This is working as expected now, updated and pushed. Please take a look,

filter_done

**Comment by jywarren** [comment]
This is awesome work. Great job! Go ahead and merge it! 🎉 🎉 🎂

**Comment by jywarren** [comment]
Some of these util functions may be great candidates for unit tests, too! Maybe as a follow-up?

**Comment by Rishabh570** [comment]
@jywarren Yes, so now I'll start adding documentation and unit tests for small pieces of code and the few remaining features will go side-by-side.

Thanks! :smile:

**Pull request merged**
