### PR TITLE
Increase code readability of src files.

### PR DESCRIPTION
**Pull request by Rishabh570**
I'll be sharing a working GIF of this PR as soon as my API quota gets refilled.

### CODE REVIEW

**Comment by Rishabh570** [comment]
@jywarren Please take a look, its working fine...

refactor

**Comment by jywarren** [comment]
Awesome!!!

**Comment by Rishabh570** [comment]
Also, I'm about to open an issue which will focus on getting all of the public's repo from Github instead of first 30...

**Comment by Rishabh570** [comment]
@jywarren Can you please take a look at the form I've submitted for GCI mentorship...I haven't received any response yet :sweat_smile: 
Thanks!

**Pull request merged**
