### PR TITLE
Added author thumbnail to issue display

### PR DESCRIPTION
**Pull request by samagragupta**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

Issue: #108

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in a uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by samagragupta** [comment]
@gauravano Please review

**Comment by Rishabh570** [comment]
Hi @samagragupta, thanks for your contribution...can you please share the screenshot of the issues' list after your changes?

**Comment by samagragupta** [comment]
@Rishabh570  https://user-images.githubusercontent.com/24359/49551137-0d91d000-f8bc-11e8-95d3-0b14ff97dc4a.png

**Comment by samagragupta** [comment]
@Rishabh570  
49551137-0d91d000-f8bc-11e8-95d3-0b14ff97dc4a

**Comment by Rishabh570** [comment]
Looks awesome :tada: Thanks!

**Comment by samagragupta** [comment]
Twitter Handle: @Samagra14

**Comment by samagra14** [comment]
Hi @samagragupta. Nice to find someone sharing the same name. Could you just remove the @ sign from the comment?

**Pull request merged**
