### PR TITLE
#128 Create CODE_OF_CONDUCT.md in Community toolbox

### LINKED ISSUE #128: Add Code of conduct to Community Toolbox
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/community-toolbox/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Create** the file named [CODE_OF_CONDUCT.md] in the `community-toolbox` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

The file needs to be created at the root of the repository and copy the code of conduct from https://github.com/publiclab/plots2/blob/master/CODE_OF_CONDUCT.md

into newly created file. 

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

### PR DESCRIPTION
**Pull request by toyblox**
Fixes #128

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by toyblox** [comment]
@publiclab/reviewers please reviews, thanks!

**Comment by gauravano** [comment]
Hi @toyblox, nice work! 

I saw you haven't marked the checklist. It's fine but I would recommend you to follow those steps as they are listed so that tasks of both reviewers and contributors can be eased.

Like, adding Fixes #[issue-number] to PR body closes the issue on PR merge. And, making a feature branch will help you in keeping your master or main branch clean and so on. 

Thanks!

**Comment by gauravano** [comment]
Merged :tada: :balloon:

**Comment by toyblox** [comment]
apologies, I was a little confused on how to contribute from the browser.  I cloned the repo at first but when running `npm install` it threw errors.  Is it better to fork, merge into my `main`, then open a PR for the base fork?  Any advice would be appreciated, feel like I missed something.  Thanks!

**Comment by gauravano** [comment]
No issue @toyblox! 

I would share my strategy of getting started with any new project.
1. Fork the project
2. Clone the project
3. Install it using given guidelines
4. At this point, I assume everything is running and I have everything up-to-date with remote. So, I make a new branch  using `git checkout -b [branch-name]`
5. Do the changes
6. Now, sometimes while doing changes and running tests, there may be some uninvited code like change to package.lock.json , etc. So, after doing my changes I run `git status` which shows me the list of changed file. I add/stage only required files using `git add [filename]`.
7. Commit the changes using `git commit -m "commit description"`
8. Push the branch to remote using `git push origin [branch-name]`

So, the branch containing the changes is now pushed to your repository. now, you can create Pull request using it with master/main branch of any organization's repo. 

I hope it helps. Thanks!

**Comment by jywarren** [comment]
Great work!!! Thanks so much!!!

**Pull request merged**
