### PR TITLE
Show number of contributors (#10) and add pagination support

### LINKED ISSUE #10: Show # of contributors at bottom of demo page
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

It's tough to quickly count the # of contributors!

## Solution

The demo page is at /index.html, and we ought to be able to add a line around here:

https://github.com/publiclab/community-toolbox/blob/master/index.html#L112-L114

to insert the # of contributors into the `h2` title, so it reads:

`Contributors (100)` (for example, if there were 100 contributors)

We'd love help with this one!

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

### PR DESCRIPTION
**Pull request by nikramakrishnan**
This fixes #10 and also adds support for GitHub paginated requests while displaying repository contributors.

Added dependency: `parse-link-header` (MIT License)

*Note*: Pages may not load in ascending order. This means page 2 might load before page 1 (top contributors) due to asynchronous nature of `request-promise`.

### CODE REVIEW

**Comment by jywarren** [comment]
This looks awesome. Do you think there are portions of this which we could build deeper into the library as separate `require`able files, so as to make the code on index.html simpler? Your code is already nicely modular!

**Comment by nikramakrishnan** [comment]
Yeah, we could put all the requesting and formatting code deeper into the library, and only expose the API that would return maybe the usernames, avatars and count.

The same can be done for any other pagination-powered API, or anything else that starts to grow bigger than we can handle on index.html.

**Comment by jywarren** [comment]
That sounds great. Would you like to give that a try before we merge this? I'm so excited for this!

**Comment by nikramakrishnan** [comment]
@jywarren I have moved all the code to `community-toolbox.js` and `ui.js`. The function is now being only called from `index.html`. Does this look fine?

**Comment by jywarren** [comment]
This is GREAT -- i'm so happy. Sorry it took me a while to circle back. Thanks so much for working on this and I'd love if you're interested in continuing to contribute on this or any other thing across Public Lab!  🎉

**Comment by jywarren** [comment]
Hmm, maybe there's an issue remaining? I pushed this to gh-pages branch but am not seeing this working here:

https://publiclab.github.io/community-toolbox/#r=all

**Comment by jywarren** [comment]
It is working locally for me!

**Comment by jywarren** [comment]
Ah oops it does work! https://publiclab.github.io/community-toolbox/

Great. It doesn't work cross-repository, but it does work normally. Awesome!

**Comment by nikramakrishnan** [comment]
Hi, it was an awesome experience working with this issue and the repo. I'm looking forward to contribute more to Public Lab, and also participate for GSoC, if the projects align with my interests!

**Pull request merged**
