### PR TITLE
add conditions to check if header contain links

### PR DESCRIPTION
**Pull request by RignonNoel**
| Q                                                      | R
| ------------------------------------------ | -------------------------------------------
| Type of contribution ?                      | Fix
| Tickets (_issues_) concerned               | #20 

---

##### What have you changed ?
Fix a JS error on contributors display when use `o` and `r` params of the index page

##### How did you change it ?
Add a condition when we get the number of page in the response of Github API since `link` param is returned **only** if we have more than **one** page (so 100 contributors in our case)

### CODE REVIEW

**Comment by jywarren** [comment]
Will review soon, thank you!!!!!!

**Comment by nikramakrishnan** [comment]
This works great! I suggest doing a `grunt build` so that the js file in `dist` is updated (for browsers).

**Comment by RignonNoel** [comment]
Oh yeah sorry @nikramakrishnan i never put the `dist` folder in my project but i forgot we use this project directly inside Github :rofl:

**Comment by RignonNoel** [comment]
@jywarren Have you some new on this PR ?

**Comment by jywarren** [comment]
Oh gosh I'm so sorry, I was in meetings all week on a trip and didn't circle back to this. It looks great, let me do a final review and merge it -- thanks so much!!!

**Comment by jywarren** [comment]
Fantastic!! 👍 🥇 Thanks so much! 

Again, apologies, I appreciate your help on this immensely!

**Comment by jywarren** [comment]
And pushed to gh-pages!

**Pull request merged**
