### PR TITLE
Add progressive web app support

### LINKED ISSUE #210: Implement PWA with caching and data fallback
This idea includes implementing a `Progressive Web App (PWA)` with the help of a service worker along with providing `offline support` and `data fallback` (data will be shown even when the user is offline).

Adding the support for _add to home screen_ is also included in this idea.

### PR DESCRIPTION
**Pull request by Rishabh570**
Fixes #210 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Rishabh570** [comment]
This PR is also ready for review, it includes adding Progressive Web App support along with dynamic caching scheme which allows offline access to the page (provided that it should be visited at least once when online). Adding to the home screen is also incorporated which is achieved with the help of `manifest.json`.

offline_working

@jywarren Please take a look :)

**Comment by jywarren** [comment]
This is looking great. I wrote up this brief thing on PWA UIs, and would love your thoughts on it! https://publiclab.org/notes/warren/08-19-2019/ui-principles-for-offline-apps @HarshKhandeparkar maybe you're interested too? 

What do you think?

**Comment by HarshKhandeparkar** [comment]
Sure, I'll have a look.

**Comment by Rishabh570** [comment]
Hi @jywarren, can we go ahead with this?

**Comment by jywarren** [comment]
Sure!!

**Pull request merged**
