### PR TITLE
Add Facebook and Twitter icon at the footer for GCI

### LINKED ISSUE #77: Add Facebook and Twitter icon at the footer
### Please describe the problem (or idea)
Visit https://code.publiclab.org/ and observe the functionality at the footer for other icons and add the same functionality for Facebook and Twitter icon.

**Facebook** :  https://www.facebook.com/PublicLab/

**Twitter** :  https://twitter.com/PublicLab?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor
> What happened just before the problem occurred? Or what problem could this idea solve?
screenshot 248

> What did you expect to see that you didn't?
look

### Please show us where to look

https://code.publiclab.org/

### What's your PublicLab.org username?
dynamic_daksh
> This can help us diagnose the issue: 

### Browser, version, and operating system
Version 70.0.3538.67 (Official Build) (64-bit)
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by pabisovsky**
Hello! I edited footer in index.html for task :) Look at this!

Fixes #77

### CODE REVIEW

**Comment by avsingh999** [comment]
@pabisovsky  great work,
please add issue number and a screenshot/gif it would be easy to us 
thanks :smile:

**Comment by DakshGondaliya** [comment]
It looks good to me.
@pabisovsky nice work.

**Comment by DakshGondaliya** [comment]
@pabisovsky mention Fixes #issueno in your first comment.

**Comment by jywarren** [comment]
Would you mind adding a screenshot? Thank you!!!

**Comment by jywarren** [comment]
Hi, i've added `fixes #77` to the description and will merge this now - but please be sure to upload a screenshot and include this `fixes #____` in future pull requests, thank you!!!

**Comment by pabisovsky** [comment]
hello! My twitter profile is: https://twitter.com/oskryptowany

**Comment by joyofsoy** [comment]
> hello! My twitter profile is: https://twitter.com/oskryptowany

We'd love to thank you on Twitter, but this Twitter handle didn't work. Is there another account?

**Pull request merged**
