### PR TITLE
Fix issue of extra margin in bottom

### PR DESCRIPTION
**Pull request by subhahu123**
Fixed Issues : #90 
##Description of Changes
removing extra margin in bottom by changing demo.css file

##Before changes
screenshot from 2018-11-12 00-38-06
##After Changes
screenshot from 2018-11-12 00-38-52

LGTM
@ajzliu @Rishabh570 @pabisovsky @radheyshyamjangid @starkblaze01 @faithngetich  @VaaibhaviSingh

### CODE REVIEW

**Comment by subhahu123** [comment]
@publiclab/reviewers please review

**Comment by subhahu123** [comment]
LGTM @jywarren @icarito @phillipesouza @pablohildo

**Comment by subhahu123** [comment]
@Rishabh570 
merge this

**Comment by Rishabh570** [comment]
Let others have their POVs first...

**Comment by subhahu123** [comment]
@Rishabh570  
NO review still

**Comment by subhahu123** [comment]
@Rishabh570 
this repository do not response

**Comment by Rishabh570** [comment]
Pinging @publiclab/reviewers

**Comment by jywarren** [comment]
Hello @subhahu123 - thank you for your contributions. Please be patient as Public Lab coding is almost entirely a volunteer effort, and a day or two may go by before you get a response, depending on how busy people are. Also, while we understand if you're frustrated, please [take a look](https://publiclab.org/conduct) at our Code of Conduct, and keep in mind that it's important to be respectful and friendly in this community. We deeply appreciate your help in this.

I'll take a look now!

**Comment by jywarren** [comment]
Great, thanks again!

**Pull request merged**
