### PR TITLE
Migrated from Travis CI to Github Actions

### PR DESCRIPTION
**Pull request by Swayamsvk**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #427 
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi! This looks all good, but it didn't run... odd! I wonder if it's a security feature: https://securitylab.github.com/research/github-actions-preventing-pwn-requests

So i tried adding a commit so it'd be from my account, but that didn't seem to work. I also can't open a new PR myself from your commits. ☹️ 

What do you think we should do? I could copy your file and open a new one but you wouldn't get credit for it. Is there any way around this you can see?

**Comment by jywarren** [comment]
I guess I could probably rebase it and open a new PR with the rebase?

**Comment by Swayamsvk** [comment]
Actually, I am dealing with this kind of issue for the first time. I read the docs and implemented it. I just want to make valuable contribution to this project. Do whatever you think is possible.And please tell me if you need me to do anything.

**Comment by Swayamsvk** [comment]
I am really sorry for the mistake I accidentally pushed my main branch and I was not able to restore it so I have to delete this branch

**Pull request closed without merging**
