### PR TITLE
Fix spelling on "Recent contributors" Permalink on Navbar

### PR DESCRIPTION
**Pull request by adeola-dev**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Aha sorry - we need to fix this unrelated git protocol error, i'll see what i can do!

```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t git://github.com/jywarren/github-api-simple.git
npm ERR! 
npm ERR! fatal: remote error: 
npm ERR!   The unauthenticated git protocol on port 9418 is no longer supported.
npm ERR! Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
npm ERR! 
npm ERR! exited with error code: 128
```

**Comment by jywarren** [comment]
Oops, i must've done that wrong... let me see...

```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/jywarren/github-api-simple.git
npm ERR! 
npm ERR! Warning: Permanently added the RSA host key for IP address '140.82.112.3' to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128
```

**Comment by adeola-dev** [comment]
Hello @jywarren, what am I supposed to do next?

**Comment by jywarren** [comment]
I'm sorry, i had to stop working on this for a bit. I just tried another fix. Fingers 🤞 

Ref: https://github.com/publiclab/plots2/pull/10841

Thank u for your patience!!

**Comment by jywarren** [comment]
Whew!!! Thank you!!! 🎉

**Comment by adeola-dev** [comment]
Thank you for the assistance @jywarren! What are the next steps to take?

**Pull request merged**
