### PR TITLE
Recent Contributors  now have link to their github profile.

### PR DESCRIPTION
**Pull request by lakshyabatman**
#75 related

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by lakshyabatman** [comment]
The issue was #75 , It was not an actual solution of the issue but thought it would be great that the recent contributors to have a link also.
simplescreenrecorder-2018-12-23_01 09 21

**Comment by Rishabh570** [comment]
Hi @lakshyabatman, you're not supposed to edit `dist/community-toolbox.js` file, instead make changes to `src/community-toolbox.js` and run `grunt build` command in the terminal...this will make changes to `dist/community-toolbox.js` automatically :)
Thanks!!!

**Comment by lakshyabatman** [comment]
Ok @Rishabh570 , I've made changes as you told. :)

**Comment by Rishabh570** [comment]
@lakshyabatman Looks good!

**Comment by Rishabh570** [comment]
@lakshyabatman Can you share a working GIF of your changes, I'll merge it then :)
Thanks!!!

**Comment by lakshyabatman** [comment]
simplescreenrecorder-2018-12-26_15 21 18

**Comment by Rishabh570** [comment]
Great! Thanks @lakshyabatman :)

**Pull request merged**
