### PR TITLE
Adding "Go to Top" Button

### PR DESCRIPTION
**Pull request by nonas-hunter**
Hi, I am a Google Code-In Participant.

I am fixing issue #80 (creating a "go to top" button)

Here are the features of my button:
- The button fades in as the user scrolls down
- The button fades out as the user scrolls up
- When the user hovers over the button it turns dark grey
- When the button is pressed the page smoothly scrolls to the top as button shrinks and then pops
- The popping animation is hand made (no need to worry about copy right)
- Works on multiple platforms

Hope you enjoy.

### CODE REVIEW

**Comment by subhahu123** [comment]
@nonas-hunter   
give the preview link So it's easy to see your changes or make a gif of your changes

**Comment by nonas-hunter** [comment]
Definitely!

Here is a gif of what I made:

giphy

**Comment by subhahu123** [comment]
its fine for merge

**Comment by Rishabh570** [comment]
@nonas-hunter There is already a PR open for it, which is going under review...it is highly advised not to open duplicate PRs as it wastes everybody's time and your effort...
There are various open issues you can work on, take a look at them here: https://code.publiclab.org/

**Comment by DakshGondaliya** [comment]
@jywarren @SidharthBansal It looks good to me.
It's ready to merge.

**Comment by jywarren** [comment]
Hi, folks, indeed, there is another solution open over here: https://github.com/publiclab/community-toolbox/pull/91

Since @anujji1999 claimed the issue first, we'd really like to get their solution merged. Would you be able to advise @anujji1999 on how you got the smooth motion in the return-to-top, and we can merge in a collaborative solution between you two? That would be in the spirit of cooperation and we would really appreciate this approach rather than feeling competitive. @nonas-hunter @anujji1999 what do you say? Work together?

**Comment by nonas-hunter** [comment]
Hi everyone,

Sorry @jywarren and @Rishabh570 for all the confusion. I thought that it was required as apart of the Google Code-In Contest to submit a pull request of your solution.

My work for the contest has just been reviewed and approved by @DakshGondaliya (many thanks) and I will close this pull request.

@anujji1999 if you are interested in making it scroll more smoothly, an easy solution would to replace the current `onclick` function you have in the html file with the following:

`onclick="window.scroll({
  top: 100,
  left: 100,
  behavior: 'smooth'
});"`

This will add the smooth scrolling. I will also add this to PR #91

**Comment by jywarren** [comment]
No issue, thank you! We're happy to give credit to both of you if both are
participating in GCI. Thank you!

**Pull request closed without merging**
