### PR TITLE
Add a list of stale issues

### LINKED ISSUE #205: Generate a list of stale issues
Creating a list of stale issues will make the issues that haven't seen any progress noticeable by other people of the community. It will surely be helpful and we would know where and who is stuck on which issue.

### PR DESCRIPTION
**Pull request by Rishabh570**
Fixes #205 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Rishabh570** [comment]
@jywarren @publiclab/reviewers Please take a look here, this is ready.
Changes live here: http://rishabh570.me/community-toolbox/

**Comment by sashadev-sky** [comment]
@Rishabh570 one thing I think it exacerbates though is that the page is getting too long. What would you think of addressing #127 next?

**Comment by Rishabh570** [comment]
Thanks @sashadev-sky, I totally agree that page is really getting long. What if we add pagination for that, like only 10 stale issues per list and one can click next for more. Maybe later we can implement pagination for every list (like contributors, ftos, candidates, recent contributors)

I can work on this next if we all decide to...what do you think?

**Comment by Rishabh570** [comment]
@jywarren Is it ready to merge?

**Comment by jywarren** [comment]
A couple suggestions - could we add a brief definition for "stale", so people know how these get sourced, and for the page getting long, we could have height = 1000 and overflow:scroll for each issues listing, what do you think? That could be simpler than pagination, although we'd want to be sure people know it's scroll-able!

**Comment by Rishabh570** [comment]
Yeah, sounds good. Setting overflow is easier than pagination.

> could we add a brief definition for "stale"

What about something like, "this list contains issues which haven't been updated from the past 10 days"...this can be added as a note?

**Comment by Rishabh570** [comment]
Here's how it looks,

Screenshot from 2019-06-10 21-52-39

The scrollbar is pretty much visible but we can make it scroll just a little bit when a user hovers over it so that he/she notices it...what do you think?

**Comment by Rishabh570** [comment]
Autoscroll will surely catch the user's attention, it would look something like,

autoscroll

So as soon as the user hovers over the `stale issues` section, the scroll movement will make him/her notice that the list is scrollable...

**Comment by Rishabh570** [comment]
Hi @jywarren, should I include the changes responsible for that last GIF, in this PR?

**Comment by Rishabh570** [comment]
@jywarren Please review it also, I need to push if the changes look good. What do you think about the auto scrolling of the list...should we include it?

**Comment by jywarren** [comment]
This is so lovely. I really like the autoscroll touch. Fantastic work!!!

**Comment by Rishabh570** [comment]
I haven't pushed latest code here, if the latest GIF looks good I can push a fresh version here.

**Comment by jywarren** [comment]
Yes please!

**Comment by Rishabh570** [comment]
Added stale issues counter also,

staleAutoScroll

**Comment by Rishabh570** [comment]
@jywarren Ready. This and FTO authors' PR are ready for review. I'll be opening a PR for recent Contributors' logic refactorization which will allow us to be in a better position while writing code for various query times in the recent contribs list.

**Comment by Rishabh570** [comment]
@jywarren Please take a final look here :)

**Comment by Rishabh570** [comment]
@jywarren Is it ready to merge?

**Comment by jywarren** [comment]
:-) so awesome! Thank you!

**Comment by jywarren** [comment]
Can you publish to gh-pages? Maybe you should consider writing a blog post on publiclab.org describing the new features here!

**Comment by Rishabh570** [comment]
@jywarren Pushed to `gh-pages` just now...yes I'll be writing a blog post about the work I've completed till now :)

**Comment by jywarren** [comment]
It looks awesome!!!!

**Pull request merged**
