### PR TITLE
[WIP] Recent month contributors show up against URL queries.

### LINKED ISSUE #9: Ability to set time range in queries: "weekly" + "monthly"
We often want to look at a portrait of the community for a specific time range. The API and [options hash](https://github.com/publiclab/community-toolbox/blob/master/src/community-toolbox.js#L8) don't seem to have a time domain, however:

https://developer.github.com/v3/repos/
https://github.com/MichielvdVelde/github-api-simple

Either we need to find how to make a time-bounded API query, or we may be able to manually filter results by timestamp. 

Let's start with `getRepoContributors()`, since it's VERY useful to be able to see how many people contributed in a specific time range:

https://github.com/publiclab/community-toolbox/blob/master/src/community-toolbox.js#L32

### PR DESCRIPTION
**Pull request by Rishabh570**
Fixes #9 
 
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

@publiclab/reviewers Please take a look...

### CODE REVIEW

**Comment by Rishabh570** [comment]
Here is the working GIF for recent contributors last month (while making this GIF, I collected recent contributors from five repos only just to stay under API limits, it is working fine otherwise...)

issues_9

**Comment by jywarren** [comment]
See here! https://github.com/publiclab/plots2/issues/3858

**Comment by Rishabh570** [comment]
@jywarren I've added a toggle button, please take a look

toggle_contribs

**Comment by jywarren** [comment]
Cool, i think it could just be a link, instead of a button, to keep the
design simple... Then it could go on the same line, like:

...week. (*see monthly*)

**Comment by Rishabh570** [comment]
@jywarren Here it is

toggle_final

**Comment by Rishabh570** [comment]
@jywarren What do you think? Looks good?

**Comment by jywarren** [comment]
I think it looks amazing. Ready to merge? Thank you!!!

Rishabh - you've had enough experience on this repository that you may want
to get merge privileges. I'd still appreciate your checking in with me, but
it may help things move a little faster. If you'd like this, I'd be happy
to add you to the publiclab/reviewers group and you could take  more of a
leadership role here! Much appreciated!!!

**Comment by Rishabh570** [comment]
@jywarren Ah...actually I'm doing some testing, it will take some time...

**Comment by Rishabh570** [comment]
@jywarren Please take a look :)

**Comment by jywarren** [comment]
Oops, it looks like the spinner does not get hidden once the contributors load!

https://code.publiclab.org/

Can you take another look? Also, would it be possible to center the spinner? Thanks!

**Comment by jywarren** [comment]
😄 🙌

**Comment by Rishabh570** [comment]
> Actually maybe we should create some kind of message that says "you've exhausted your quota, try again in x minutes"... you know?

I'll open an issue for it :)

**Pull request merged**
