### PR TITLE
add fto authors username

### LINKED ISSUE #415: show FTO Authors usernames in a text list above the thumbnails
Need to show FTO Authors usernames in a text list above the thumbnails, as followed in the other sections.
****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by govindgoel**
This commit adds the fto authors username before the thumbnail
fixes #415

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [X] code is in uniquely-named feature branch and has no merge conflicts
* [X] PR is descriptively titled
* [X] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by govindgoel** [comment]
>Preview
Screenshot from 2020-12-21 03-06-40

**Comment by jywarren** [comment]
Oh this looks good! Awesome! Hey, i wonder if you might be interested in helping @akanksha-v get oriented enough to take on a related improvement? @akanksha-v would you mind reviewing this pull request as well? Thank you both!

**Comment by govindgoel** [comment]
@jywarren  I will be glad to help and work on the improvements.

**Comment by akanksha-v** [comment]
@jywarren This looks great to me too. I feel we can merge this for now and I shall make a single div for all sections collectively if that sounds cool to you. @govindgoel can even help me with that.

**Comment by jywarren** [comment]
Sounds excellent, both of you, thank you and pls feel free to cc me in future issues and prs as you go!

**Pull request merged**
