### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by motorcitycode**
-      <p>No issues left? See the almost-as-good "candidates" below, or learn how to <a href="">prepare new <b>first-timers-only</b> issues here</a>.</p>
+      <p>No issues left? See <a href="/#r=all">issues across this org here</a>, and see the almost-as-good "candidates" below. Or learn how to <a href="">prepare new <b>first-timers-only</b> issues here</a>.</p>

### CODE REVIEW

**Comment by motorcitycode** [comment]
Not sure what I did, or if it was correct. Hope so. thanks.

**Comment by jywarren** [comment]
Hi -- this looks perfect; merging now. 👍 🎉  If you're looking for a new challenge, please take a look at https://code.publiclab.org#r=all; we prefer to leave `first-timers-only` issues for complete newcomers, but there are plenty of others we need help with! Thanks!

One small note is that in the future, it's very helpful for PR titles to be descriptive of what you did, even if it's a bit redundant with the original issue. Just makes it easier to skim in a list. Thank you!!!!

**Comment by motorcitycode** [comment]
I've done lots of coding over the years, but working through github is new.  Thank you for the info about the title field. What helped you learn the best practices of contributing to projects using github? I'll take a look at the link above and see if there's anything there I can do. Thank you for your help.

**Comment by jywarren** [comment]
Hi! We've collected some here - i hope they help! https://publiclab.org/developers#Resources

**Pull request merged**
