### PR TITLE
made 'connect with us' section responsive

### PR DESCRIPTION
**Pull request by ljuneaul**
I'm really sorry but I couldn't figure out how to doing below tests.
In addition, in DIFF, two lines were not marked as changed not as [example](https://github.com/publiclab/community-toolbox/issues/214).

I am so sorry if I did make any mistake.
```css
- #connectwithusbody {   // this is not marked as changed
- overflow: hidden;   // this is ok
- }   // this is not marked as changed
```
---
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by garg3133** [comment]
@ljuneaul You've done that all right. The two lines are not marked as changed because they have not actually changed but only the content between those two lines is changed.

**Comment by ljuneaul** [comment]
Thank you so much! A really learn a not including formatting and documentation!

**Comment by Rishabh570** [comment]
Hi @ljuneaul, your work looks great! Are you about to open another PR because you closed this one!?

**Comment by ljuneaul** [comment]
Ops sorry, I thought that it means that I didn’t finish the job. My apology.

**Comment by ljuneaul** [comment]
I wonder what `can you tell us your Twitter` means. Where may I tell my twitter account?
You guys are amazing. I am doing my second and this experience helping me a lot. Thank you so much.

**Pull request merged**
