### PR TITLE
List of contributors fetched and stored to localStorage

### LINKED ISSUE #53: List of contributors missing once API rate limit exceeded (message needed)
screenshot 87

Maybe the API limit has exceeded, please look into it.

### PR DESCRIPTION
**Pull request by Rishabh570**
Fixes #53

### CODE REVIEW

**Comment by Rishabh570** [comment]
@jywarren Here is the working GIF

gif_53

**Comment by jywarren** [comment]
How does this one relate to https://github.com/publiclab/community-toolbox/pull/54 ?

Thanks!!

**Comment by Rishabh570** [comment]
@jywarren #54 is for `https://code.publiclab.org#r=all` and this is for `https://code.publiclab.org/` :)

**Comment by Rishabh570** [comment]
Both solve one purpose i.e., fetch contributors and store them to localStorage to prevent network calls, but this one is for contributors that show up on `https://code.publiclab.org` page :smile:

**Comment by jywarren** [comment]
Super. I've merged this. I am a little worried that the code is starting to become difficult to read for newcomers -- do you think some additional comments, or naming functions with names like `function doThingWithEach()` instead of anonymous `function()` could help? Or potentially even breaking it up into separate descriptively named files?

Thanks!!! Also watch out that I'm renaming the `master` branch to `main` in a moment. All future PRs should be against `main`. Thank you!!!

**Comment by Rishabh570** [comment]
@jywarren I completely agree, code readability is also important...I will do whatever is necessary to make the code more readable. I'll create a PR for it...

> Also watch out that I'm renaming the master branch to main in a moment

I hope everyone knows this...

**Comment by jywarren** [comment]
It's ok - any new clones will go from main and any PRs that go to master we
can redirect. Thanks!!!

**Comment by Rishabh570** [comment]
Ah, that's great!

**Comment by Rishabh570** [comment]
@jywarren I've done some refactoring work, the corresponding PR is #63 
Please take a look, let me know if anything is needed :)

**Pull request merged**
