### PR TITLE
Add dropdown autocomplete for navigation around repositories

### LINKED ISSUE #203: Add dropdown for navigation around different repositories
Currently, if someone tries to take a look at any repository's data on `code.publiclab.org`, he/she has to manually type in the URL bar which can be uncomfortable for some of the users.

This issue is about making a dropdown button or autocomplete maybe for making the navigation across different repositories easy!

### PR DESCRIPTION
**Pull request by Rishabh570**
Fixes #203 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Rishabh570** [comment]
Here's a GIF of my changes,

dropdown

@jywarren @publiclab/reviewers I've made an autocomplete dropdown for selecting repositories because a normal dropdown would be very long taking into account the number of repositories.

**Comment by Rishabh570** [comment]
@jywarren @publiclab/reviewers Please take a look here, it is ready for review...

**Comment by Rishabh570** [comment]
Thanks @sagarpreet-chadha, is it ready to merge?

**Comment by jywarren** [comment]
This looks good! Perhaps though, we should put this further down, or under an expanding section that at first just shows the currently selected repo? And although it would be a lot, potentially without naming some of them, it would seem confusing to show an empty box. People might not know what the possibilities are? 

What if we have something that says `Showing [all repositories +]` or `Showing [mapknitter +]` -- where `[     ]` is a dropdown? I like what you've done with the autocomplete! I'm just not sure because i feel like we would need to show some kind of list. Maybe the module selector in http://sequencer.publiclab.org could be an interesting example to look at?

Great work, @Rishabh570 !!!!

**Comment by Rishabh570** [comment]
@jywarren Right, the user might not be able to figure out what to type so providing a dropdown is a better option. So I've changed it, now it looks like,

dropdown_final

I think this is easier to understand than the autocomplete, what do you think?

**Comment by Rishabh570** [comment]
Hi @jywarren, please take a look here...if the changes in my latest GIF look good I can push them.
Thanks!

**Comment by jywarren** [comment]
It looks awesome. Very cool. Thanks!!!!

**Comment by Rishabh570** [comment]
Okay, so I've pushed the latest changes, please take a look here: http://rishabh570.me/community-toolbox

**Comment by Rishabh570** [comment]
@jywarren Is it ready to merge?

**Comment by jywarren** [comment]
Yes! Do you want to go ahead?

**Comment by Rishabh570** [comment]
Sure, thanks!!! :smiley: :tada:

**Pull request merged**
