### PR TITLE
Update community-toolbox.js

### PR DESCRIPTION
**Pull request by gptshubham595**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi! What issue is this in response to? Thank you!!!

**Comment by Rishabh570** [comment]
@gptshubham595 The issue related to your PR is resolved by some other PR...
As you didn't write `Fixes #{issue_number}` in your PR description...we were not able to know that there is another PR open for that issue...

No worries, you can take a look at other issues here: https://code.publiclab.org/

PS: Please don't open two PRs for resolving a single issue and please look around for some other existing PR before working on any issue...

Thanks!!!

**Comment by gptshubham595** [comment]
Actually i only did the fix,  but forgot to mention

At first i reported issue,

Then i gone there and made it correct
I am new so i was not knowing that i have to write there only

**Comment by jywarren** [comment]
Sorry this didn't work out, but we would love to work with you on new issue. We're happy to help you learn the workflow and would be grateful for more assistance from you!

**Pull request closed without merging**
