### PR TITLE
Add list of FTO issue authors.

### LINKED ISSUE #13: Add list of authors of first-timers-only issues
As people begin taking leadership in a project, they may start to post their own first timers only issues (see [this example](https://publiclab.github.io/community-toolbox/#r=all)). It'd be helpful to list these folks at the bottom of the page, so we know who's started to play this role. 

We could title the section "Welcomers" perhaps, say `These people have spent the time to create an issue specifically to welcome first timers:` and list their usernames!

### PR DESCRIPTION
**Pull request by Rishabh570**
FIxes #13 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Exciting!!! You should mention this in this week's check-in, folks will be
very happy! Ping me when you'd like a review? Thanks a ton!!!

**Comment by Rishabh570** [comment]
Yeah, I've mentioned this in the check-in...I'll let you know when it's ready :)

**Comment by Rishabh570** [comment]
@jywarren It is ready now :smile:.

**Comment by Rishabh570** [comment]
Hi @jywarren, here's how it looks,

Screenshot from 2019-07-04 20-27-47

Is it good to go?

**Comment by jywarren** [comment]
Oh awesome! Yes! Thanks!!!

**Pull request merged**
