### PR TITLE
Resolve dropdown logic and change urlHash source.

### LINKED ISSUE #228: Issue in dropdown logic
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

There's a small issue in the `src/utils/autocomplete.js`, regarding the _urlHash_.

### Please show us where to look

https://github.com/publiclab/community-toolbox/blob/main/src/utils/autocomplete.js

### What's your PublicLab.org username?

icode365

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by Rishabh570**
Fixes #228 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Rishabh570** [comment]
@jywarren Please take a look here...

**Comment by jywarren** [comment]
Ok cool!! So will the older links still work, or are we giving that up?
Thanks Rishabh!

**Comment by Rishabh570** [comment]
Yeah, this won't affect anything related to the links, the repository name will still be there in the URL as the hash...just the source of the file will be changed from `node_modules/` to `examples/`.

**Comment by Rishabh570** [comment]
Hi @jywarren, please take a look here...once this gets merged I can update my `stale issues list PR` and `FTO issue authors list PR` and they'll be ready for review also :)

**Comment by Rishabh570** [comment]
@jywarren Should I go ahead with this one?

**Comment by jywarren** [comment]
Hi, Rishabh! So sorry... looking now.

**Comment by jywarren** [comment]
Sounds great. Let's do it. Thanks for your patience!

**Pull request merged**
