### PR TITLE
Added the Side-NavBar, fixes #339

### LINKED ISSUE #339: Adding Side-Navbar for better usability
Adding side-nav bar will enhance the usability of the website and user can easily jump through sections quickly.

Please suggest any changes or addition, I'll be adding on scroll animation though.

sidenav1

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by DevanshCodes**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes fixes #339  -style reference to original issue #
* [x] ask @publiclab/reviewers for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by cesswairimu** [comment]
Hi @DevanshCodes, thanks so much for opening this :tada: could you please add the issue link to the issue this pull request fixes on your pull request on this line "Fixes issue_link" this will help other contributors while reviewing your changes. It also helps in automatically closing the issue when the pull request is merged. Thanks

**Comment by Rishabh570** [comment]
Hi @DevanshCodes, can you please share a screenshot of your changes. Also, which issue does this PR point to? It would be great if you can reference issues in your PR desc. (Like `Fixes #{issue_number}`).

Thanks!

**Comment by DevanshCodes** [comment]
Hey, sorry for the description, fixed that. Here's the screenshot. 

sidenav_send

Thanks! :)

**Comment by Rishabh570** [comment]
Hi @DevanshCodes, this is very useful!
So, how does it behave on smaller screens...can you please share a GIF for that. Also, if you could fix the visibility issue when you hover over those links.

Thanks!!!

**Comment by jywarren** [comment]
I agree this is super nice! And would love to see some different screen sizes. Thank you!!!

**Comment by jywarren** [comment]
Hi, just wondering if a few other screen sizes could be included in screenshots? Thank you!

**Comment by DevanshCodes** [comment]
Hey @jywarren , was busy for a month because I was applying for GSoC in other Org. Now, I'm free and will look into this.

**Comment by jywarren** [comment]
awesome!!! Thanks!

**Comment by jywarren** [comment]
Hi, it looks like @YogeshSharma01 is working on a top navbar now. I'm going to close this but we'd still love your help! Thank you very much!

**Pull request closed without merging**
