### PR TITLE
Add leaderboard of recent contributors

### LINKED ISSUE #207: Implement a leaderboard of contributors
This idea is about making a leaderboard of contributors last week/last month. This would provide inspiration to the new contributors and a sense of healthy competition will surely increase the productivity of people. As of now, we get the list of contributors last week and last month, that would help in extracting the list of super helpful contributors.

It turns out that the logic of fetching `recent-contributors` can be useful for leaderboard also, so no need for whole another mechanism. Recent contributors' data can be stored while fetching them and it can be used to generate a list of the leaderboard of our contributors.

### PR DESCRIPTION
**Pull request by Rishabh570**
Fixes #207 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Rishabh570** [comment]
@jywarren I'm thinking of providing `create leaderboard` option in the `recent contributors` filter dropdown that I'm about to add because if we show both (recent contributors & leaderboard list) at the same time, it looks like some duplicate list when looked superficially. On the other hand, if we provide the option of showing leaderboard as an option in the filter section people will know that the list is about to get filtered according to the leaderboard criteria/logic and it will look better because there'll be only one list getting updated instead of two separate lists for recent contributors and leaderboard.

Currently, two separate lists look like this,

Screenshot from 2019-07-16 10-54-31

I guess providing create leaderboard option in the filter button would make it clean and easily comprehensible, what do you think?

**Comment by jywarren** [comment]
Yeah, i think that is a good solution! Thanks for thinking this through
carefully!

**Comment by Rishabh570** [comment]
leaderboardGIF

@jywarren This is done, please take a look here. Also, I'll be pushing tests for `utils/` in the coming days just some work is remaining. By tommorow, it will be done most probably :)

Thanks!

**Comment by jywarren** [comment]
This sounds great! Let's merge! I love the dropdown styling :-)

Perhaps after the utils work, we should start adding small "code" icons to
offer embed codes for things. See how there is a `</>` type icon to bottom
right of the tables on pages like these? https://publiclab.org/coqui

We could make this pop up a URL that can be copy-pasted somewhere else, so
people can embed community toolbox on their own sites. And, we should force
the URLs not to use defaults, so that the repository and organization are
clear in the URL, so people can change them. What do you think?

Great work, Rishabh!

**Comment by Rishabh570** [comment]
Yeah, that will make using community toolbox even easier and faster...they just need to copy-paste embed link for the feature they want, interesting!

I'm done with tests for `utils/` and currently working on documentation...this would be perfect next milestone.

Thanks! :smiley:

**Pull request merged**
