### PR TITLE
[WIP] Show contributors last week at bottom of page

### LINKED ISSUE #57: Show list of "contributors this week" separated out from "for all time"
more soon! It'd be helpful to see recent activity 👍

### PR DESCRIPTION
**Pull request by Rishabh570**
Fixes #57 
@jywarren This PR achieves what is the issue was about but there's a problem, we can't make so many unauthenticated requests to the Github API and fetching contributors (on `code.publiclab.org` and `code.publiclab.org#r=all` page) empties the hourly quota i.e., 60 requests. After all of this, making a chunk of requests for commits of all the repos will surely get us **403**

Btw here is the working GIF,

issue_57_3

### CODE REVIEW

**Comment by jywarren** [comment]
Sorry I'm on my phone so can't read code easily, but couldn't we record
last date of interaction on the initial request rather than running new
requests?

Thanks!!!

**Comment by Rishabh570** [comment]
Yes, we just have to fetch the commits one time, after that they get stored to localStorage along with the the time (in epoch)...we make a fresh request after every 24hrs.

**Comment by jywarren** [comment]
Ah, so does this PR do that or is it a different implementation? Thanks for
explaining! I'm on a train without good internet. Thanks!

**Comment by jywarren** [comment]
Also, Rishabh, you are doing so much for this repository. Perhaps you'd
like to be a collaborator on it so you can tag issues and do reviews and
such? :-)

You probably know the code better than I at this point!

**Comment by jywarren** [comment]
Once we have this feature by the way, we'll be able to do things like send
a weekly email to new contributors from the past week easily, and a
modification could let us see who's written a first timers only issue in
the past week. We could make a nice section of the welcome page just for
helping organize welcomers and such :-)))

**Comment by Rishabh570** [comment]
> Ah, so does this PR do that or is it a different implementation? 

This PR includes that :)

**Comment by Rishabh570** [comment]
> Once we have this feature by the way, we'll be able to do things like send a weekly email to new contributors from the past week easily, and a modification could let us see who's written a first timers only issue in the past week. We could make a nice section of the welcome page just for helping organize welcomers and such :-)))

Sure, we'll go step by step :)

**Comment by Rishabh570** [comment]
@jywarren To stay within API limits, I've taken 25 most active repos to get contributors from, 20 repos to get recent commits from...maybe we can increase 20 to 25 later (I need to do some testing for that).
But the effect is not much noticeable...Please take a look...

ezgif com-optimize

**Comment by Rishabh570** [comment]
@jywarren Here is the working GIF, it turns out that it's not possible to increase the number of requests we make so now there are 20 repos from which we fetch all the contributors and recent contributors...but it didn't affect the output so much so it is okay I guess...please take a look,

output_nch18k

**Comment by jywarren** [comment]
Wow, this is great. Do you think it's ready to merge, then?

**Comment by Rishabh570** [comment]
@jywarren Yes, its all set!!

**Comment by jywarren** [comment]
Awesome! I will publish shortly!

**Pull request merged**
