### PR TITLE
add night mode theme.

### LINKED ISSUE #155: Add dark theme
### Please describe the problem (or idea)
I think if we can add a change theme button and the theme will be a toggle to the dark theme. It would be a better UI.
> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://code.publiclab.org/ 

### What's your PublicLab.org username?
singhav
> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by Rishabh570**
Fixes #155 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Rishabh570** [comment]
nightModeWork


@jywarren @publiclab/reviewers This is ready, please take a look...

**Comment by Rishabh570** [comment]
Actually, a slide toggle would look better and will be better suited for this use case. How about this,

night_toggle_work

The toggle remembers the user's last choice and adjusts accordingly after reload.
@jywarren @publiclab/reviewers Please have a look :)

**Comment by jywarren** [comment]
Haha! So cool! Let's do it!

**Comment by Rishabh570** [comment]
@jywarren I've pushed the latest changes here, you can take a look [here](http://rishabh570.me/community-toolbox/). It is ready.

**Comment by sashadev-sky** [comment]
@Rishabh570 love this feature!

**Comment by sashadev-sky** [comment]
Dan Abramov (React creator) does a cool job at this too on his site and uses little night and day symbols: https://overreacted.io/

**Comment by jywarren** [comment]
This is so beautiful! Great work!

**Pull request merged**
