### PR TITLE
Add notifications for user acknowledgement

### LINKED ISSUE #206: Add user notifications
Currently, the user is not able to know if anything goes wrong while showing the data to the website and he/she keeps trying again & again which is not good.

`User notifications` will let the user know when any part of the data (like the list of contributors, list of recent contributors, issues, etc.) doesn't get rendered...this will make sure that the user is not wasting time waiting for it to show (data).

### PR DESCRIPTION
**Pull request by Rishabh570**
Fixes #206 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Rishabh570** [comment]
@jywarren Please take a look here...almost done, just some little changes are remaining. These notifications will tell the user if anything unexpected happens due to **network/API reasons**.

not gif 2

**Comment by jywarren** [comment]
Ah, that's really nice. Is it ready for a final review? Could you try
asking in the chatroom for a reviewer? Thanks!!

**Comment by Rishabh570** [comment]
It'll be ready by tomorrow, I'll also tag reviewers here once it is ready. :+1:

**Comment by Rishabh570** [comment]
@publiclab/reviewers This is ready for review. Please take a look.

**Comment by jywarren** [comment]
:-) looks great! Go ahead and merge!

**Comment by Rishabh570** [comment]
Thanks! :tada:

**Pull request merged**
