### PR TITLE
Footer UI changes

### PR DESCRIPTION
**Pull request by pydevsg**
Solved Issue #254 
Removed extraordinary line and center aligned the texts to make the UI look beautiful.

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by gauravano** [comment]
Hi @pydevsg, please attach screenshot/GIF of final UI, displaying change across all screens. Thank you!

**Comment by pydevsg** [comment]
Okay, @gauravano I will do the same.

**Comment by Rishabh570** [comment]
Hi @pydevsg, can you please share a screenshot for your changes, feel free to ask if you're having any issue.

**Comment by pydevsg** [comment]
Yeah, sure I am sending it.

**Comment by pydevsg** [comment]
This is the how the footer is looking now in different screen sizes. Hope its fine now 😅 
- Galaxy 
galaxy

- iPhone 6/7/8
iphone6 to 8

- iPhone X
iphoneX

- iPad Pro
iPad Pro

- Dell Inspiron Laptops
Dell Inspiorn 14 series laptops

- Medium SIzed Laptops(15.6')
Medium Sized Laptops(15 6')

**Comment by Rishabh570** [comment]
Changes look good, nice work @pydevsg! Just to confirm, are these icons centered on the smaller screens?

**Comment by pydevsg** [comment]
Thanks @Rishabh570 , yes they are centered in small screen.

**Comment by pydevsg** [comment]
@gauravano please merge my PR if everything seems alright

**Comment by Rishabh570** [comment]
Thanks for your contribution @pydevsg :tada:

**Comment by gauravano** [comment]
Great work @pydevsg! Please use Fixes #[issue number] in the PR body as that close the issue when PR gets merged. Thanks!

**Comment by pydevsg** [comment]
> Great work @pydevsg! Please use Fixes #[issue number] in the PR body as that close the issue when PR gets merged. Thanks!

Okay thanks for the suggestion @gauravano .

**Pull request merged**
