### PR TITLE
Add a copy to clipboard button

### LINKED ISSUE #209: Add a copy-to-clipboard button
Adding a copy to clipboard button can be very useful when someone needs to copy paste the names of contributors and this would allow us to change our contributor list UI also

### PR DESCRIPTION
**Pull request by Rishabh570**
Fixes #209 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Rishabh570** [comment]
@jywarren @publiclab/reviewers This PR adds copy to clipboard functionality to the contributors' names section,

Screenshot from 2019-07-07 08-39-01

Please take a look.

**Comment by jywarren** [comment]
Oh, AWESOME! +1000000 !

**Comment by Rishabh570** [comment]
@jywarren Should I go ahead with the merge?

**Comment by jywarren** [comment]
yes please! Thanks Rishabh!

**Pull request merged**
