### PR TITLE
Desigining view of all contributor section

### LINKED ISSUE #150: Changing Contributors List UI To Bootstrap Card
### Please describe the problem (or idea)

Currently view or the way website presents the list of contributors is very
Instead of that we can use bootstrap card for good view or desiging the lists of contributors

### PR DESCRIPTION
**Pull request by subhahu123**
Fixes #150

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

## before
screenshot-code publiclab org-2019 03 03-04-01-18

## after
screenshot-127 0 0 1-5500-2019 03 03-03-20-55

### CODE REVIEW

**Comment by subhahu123** [comment]
@jywarren please review and merge this

**Comment by jywarren** [comment]
Hi! Thanks so much for your help!

Actually the list at the top is intended to be easier to select as text, so you can copy it into an issue and alert people. If you'd like to remove it, perhaps we could change that to a button which opens it in a modal, or an alert box, so that it can be selected and copy-pasted? However, I like what you've done with the names being next to the pictures, so as long as we resolve the copy-paste issue, we could adopt this too! 

How does that sound?

**Comment by subhahu123** [comment]
> Actually the list at the top is intended to be easier to select as text, so you can copy it into an issue and alert people. 

????????????????? sry i did't get this

**Comment by subhahu123** [comment]
> Hi! Thanks so much for your help!
> 
> Actually the list at the top is intended to be easier to select as text, so you can copy it into an issue and alert people. If you'd like to remove it, perhaps we could change that to a button which opens it in a modal, or an alert box, so that it can be selected and copy-pasted? However, I like what you've done with the names being next to the pictures, so as long as we resolve the copy-paste issue, we could adopt this too!
> 
> How does that sound?

we can either use toggle view or can create a copy button which will automatically copy all the names

**Pull request closed without merging**
