### PR TITLE
fixes: #564 Grouped similar inline style rule into demo.css

### PR DESCRIPTION
**Pull request by on2onyekachi**
The first commit fixes: #564,

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by TildaDares** [comment]
Hi @on2onyekachi, can you add the issue number to the description above? Thanks!!

**Comment by on2onyekachi** [comment]
Okay @TildaDares, That has been fixed. though this PR has 2 commits for different issues.

**Comment by TildaDares** [comment]
Hi @on2onyekachi, it's better if PRs solve only one issue/problem. It's a lot easier to review that way. Thank you!!

**Comment by on2onyekachi** [comment]
Okay, @TildaDares I really didn't realize there was a pending PR from the same branch. Not until after the push. sorry for that. Please how can I go about redoing this?

**Comment by TildaDares** [comment]
@on2onyekachi I don't have any experience with splitting commits into different branches but you can checkout this [SO answer](https://stackoverflow.com/questions/31242719/split-commits-into-two-branches).

**Comment by TildaDares** [comment]
@on2onyekachi I don't have any experience with splitting commits into different branches but you can checkout this [SO answer](https://stackoverflow.com/questions/31242719/split-commits-into-two-branches).

**Comment by on2onyekachi** [comment]
Thanks for the resource @TildaDares. It helped and I have split the commits into two different branches. please review

**Review by TildaDares — APPROVED** [review]
Thanks @on2onyekachi!!

**Pull request merged**
