### PR TITLE
Fix site issues [403 errors]

### LINKED ISSUE #112: Contributors list is empty - error?
Hmm, at https://code.publiclab.org#r=all, i'm seeing nobody in the contributors list; same in incognito mode. I haven't loaded it for days, so I don't think it's queue exhaustion. Anyone have ideas? @Rishabh570 maybe?

Thanks!

screenshot 2019-01-02 at 5 35 57 pm

### PR DESCRIPTION
**Pull request by Rishabh570**
Fixes #112 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Rishabh570** [comment]
@jywarren I've opened up this PR which resolves #112, it reduces recent contribs request count to half of its previous value and only requests 4 pages of data for `plots2` contributors because any other repo does not need multiple requests actually, that's a good thing...also, the changes are live at https://rishabh570.github.io/community-toolbox
Please take a look when you find time :)

**Comment by jywarren** [comment]
This looks great and works perfectly. Shall we add + to the number to
acknowledge that we may not be counting every last person? So like 438+?

Thanks!!! Great work fixing this!

**Comment by Rishabh570** [comment]
Sure!

**Comment by jywarren** [comment]
OK awesome. Is this ready to merge? Go ahead if so, and I can publish to gh-pages too!

**Comment by Rishabh570** [comment]
@jywarren Merged!

**Pull request merged**
