### PR TITLE
JS code enhancement

### LINKED ISSUE #297: Javascript Code enhancement
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

Currently, the codebase has used the keyword 'var' which is outdated. I intend to replace those with 'let' and 'const' which are JS standard now.

### Please show us where to look

https://code.publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

Browser:Chrome
OS: Ubuntu

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by somenath1435**
fixes #297 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

**Comment by somenath1435** [comment]
@jywarren @Rishabh570 please review

**Comment by somenath1435** [comment]
@Uzay-G It's already done...See this PR..Thanks

**Comment by somenath1435** [comment]
@Rishabh570 every thing is working fine

**Comment by somenath1435** [comment]
@jywarren @Rishabh570 I think this PR is good to be merged

**Comment by Rishabh570** [comment]
Thanks @somenath1435, merging this :tada:

**Pull request merged**
