### PR TITLE
moved link tags to the head. this fixes #550

### LINKED ISSUE #550: Move link tags from body to the head section in index.html
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

`<link>` tags are placed in the `<body>` element. which still works fine and is permitted in the `<body>`. 

Screenshot 2022-04-01 at 12 29 15

> What did you expect to see that you didn't?

However, I expected to see the `<link>` tag placed in the `<head>` element.  
Screenshot 2022-04-01 at 12 39 27

### Please show us where to look

[index.html](https://github.com/publiclab/community-toolbox/blob/main/index.html)

### What's your PublicLab.org username? 
Thekachi

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by on2onyekachi**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #550 `-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by TildaDares** [comment]
@on2onyekachi Can you add the link to the issue being resolved?

**Comment by on2onyekachi** [comment]
> @on2onyekachi Can you add the link to the issue being resolved?

Oh, Thanks. I think it's linked already.  #550

**Review by TildaDares — APPROVED** [review]
Thanks @on2onyekachi!!

**Comment by on2onyekachi** [comment]
> Congratulations tada

Thank you for the support. @TildaDares

**Pull request merged**
