### PR TITLE
Adding travis ci and surge link

### PR DESCRIPTION
**Pull request by subhahu123**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by jywarren** [comment]
Wow, very cool! https://surge.sh/

@Rishabh570 what do you think?

**Comment by subhahu123** [comment]
@jywarren i want to work on the gsoc project of community toolbox
I want to know what we have to do in our project more
So that i can start writing proposal
And what about template or format of propos

**Comment by jywarren** [comment]
Hi! Thank you for your interest!!! Please check out this page for
more information on GSoC!
https://publiclab.org/notes/warren/02-28-2019/call-for-summer-of-code-2019-proposals
Thanks!!

**Comment by subhahu123** [comment]
@subhahu123  which is mvc framework we should use for this project 
like angular , react , ember or vue 
i know angular and react and can work with it 
which is better framework we should use for this project 
what do u think ?

**Comment by Rishabh570** [comment]
> @Rishabh570 what do you think?

@jywarren Ah, surge.sh looks a good fit for our needs...interesting!

**Comment by gauravano** [comment]
Hey @subhahu123, please remove the merge conflicts. Thanks!

**Comment by subhahu123** [comment]
> Hey @subhahu123, please remove the merge conflicts. Thanks!

@gauravano  done

**Pull request closed without merging**
