### PR TITLE
restyle missing avatar images as grey circles

### LINKED ISSUE #411: restyle missing avatar images as grey circles
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [src/UI/issuesUI.js](https://github.com/publiclab/community-toolbox/blob/main/src/UI/issuesUI.js) in the `community-toolbox` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -24,7 +24,7 @@ function insertIssue(issue, el) {
       body += "<a class='label label-default' href='" + label.url + "' style='background:#" + label.color + ";'>" + label.name + "</a> ";
     });
     body += "</div>";
-    body += "<img src='https://github.com/"+ issue.user.login + '.png' + "' width='45px' height='45px' style='margin-right:15px;' >";
+    body += "<img src='https://github.com/"+ issue.user.login + '.png' + "' width='45px' height='45px' style='border-radius:100%;background:#ccc;margin-right:15px;' >";
     body += "<b>#" + issue.number + "</b> opened " + moment(issue.updated_at).fromNow() + " ";
     body += "by <a href='https://github.com/" + issue.user.login + "'>" + issue.user.login + "</a>";
     body += " <i class='fa fa-comment-o'></i> " + issue.comments;
@@ -47,4 +47,4 @@ module.exports = {
     generateIssueHtml: generateIssueHtml,
     insertIssue: insertIssue,
     insertStale: insertStale
-};
\ No newline at end of file
+};
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by akanksha-v**
Fixes #411 

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by govindgoel** [comment]
@akanksha-v it is not required to open a new pr every time, you could have updated the previous one itself.

**Comment by akanksha-v** [comment]
@govindgoel yes I shall take care of that from next time. Thank you so much and yes I can share the screenshot of the changes:
circles-picture

**Review by govindgoel — APPROVED** [review]

**Comment by akanksha-v** [comment]
Hi @jywarren please review this :)

**Review by jywarren — APPROVED** [review]
Looks great!!!! Thank you!

**Comment by jywarren** [comment]
Well done!!!!

**Comment by jywarren** [comment]
Would you like to try a new one? I'm wondering if we could make one for either:

1. adding text to explain the time frame for the `FTO Authors` section -- is it the last 2 weeks?
2. showing FTO Authors usernames in a text list above the thumbnails, like we do for other sections, so they can be easily copy/pasted

@govindgoel i don't know if you are familiar enough with the codebase to try to find starting points for these? Or perhaps someone else who's recently worked on the codebase here? 

Thanks, all!!!!

**Comment by govindgoel** [comment]
@jywarren Will surely do these enhancements, opening up an issue, and will work on it. 
The timeframe for FTO authors I need to check and will update the same.

**Comment by akanksha-v** [comment]
@jywarren Thanks for merging my pr and yes I would love to contribute more to this project.
If issues are created for the above-mentioned points then I would definitely like to work upon these : )

**Comment by jywarren** [comment]
oh that's wonderful both of you. If either of you get stuck or run out of
time i'm happy to pitch in as well, don't hesitate to ping me here or in
https://gitter.im/publiclab/publiclab

thank you!

**Pull request merged**
