### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by gptshubham595**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, would you be able to mention which issue this is in response to? Thank
you!!!

**Comment by Rishabh570** [comment]
Hi @gptshubham595, are you on it? This PR has some conflicts, please can you take a look...
Also, share a working GIF for your changes...That would make review easy :)

**Comment by gauravano** [comment]
Hi @gptshubham595, can you mention the issue number this PR is trying to solve and please resolve the merge conflicts too. If you need any help, feel free to ask. Thanks!

**Comment by gauravano** [comment]
Closing this PR as the contributor has not responded. Thanks!

**Pull request closed without merging**
