### PR TITLE
Refactor the codebase

### LINKED ISSUE #201: Refactor the codebase
The current state of the code is not friendly for code reading. Also, naming conventions are confusing at some points in the code and big chunks of code need to be divided into more manageable parts.

### PR DESCRIPTION
**Pull request by Rishabh570**
Fixes #201 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Rishabh570** [comment]
@jywarren @sagarpreet-chadha @harshithpabbati I've opened this PR for #201, please take a look.

Sorry, I've made a single commit for all of it, I can break it down into smaller commits if you want...

Here is my `gh-pages` link for current changes: http://rishabh570.me/community-toolbox/

**Comment by jywarren** [comment]
Oh wow! Huge!

So, this is awesome. I did get some kind of error here, though - can you take a look?

image


Great work!!!

**Comment by Rishabh570** [comment]
@jywarren Hmm, I'm not facing this error, I guess hard refreshing the page would resolve this error...I'll take a look.
Thanks :smiley:

**Comment by Rishabh570** [comment]
or maybe disabling the browser cache from network tab...

**Comment by Rishabh570** [comment]
Hi @jywarren, I've made a GIF of how these changes work in my local version of the site...I don't know why `gh-pages` is not reflecting the latest changes. Please take a look,


REFACTOR_GIF

**Comment by Rishabh570** [comment]
Pinging @jywarren @publiclab/reviewers, please take a look :)

**Comment by rexagod** [comment]
@Rishabh570 Can you verify if your promises are getting resolved properly? Skimming through the errors this seems to be an async issue.

**Comment by Rishabh570** [comment]
@rexagod yeah so the errors showing up on @jywarren 's screenshot were related to database setting up...actually if we try to do any kind of db operation while db is setting up (it takes some time to set-up, some milliseconds) that error gets showed up. But that's not from my current changes as I've shared a screenshot above that doesn't contain those errors...

**Comment by Rishabh570** [comment]
But don't know why `gh-pages` are not reflecting that...

**Comment by rexagod** [comment]
> actually if we try to do any kind of db operation while db is setting up (it takes some time to set-up, some milliseconds) that error gets showed up

Did you set up some sort of async wrapper to handle this? If no, consider wrapping this in a async/await function, or maybe return a promise even. But if you have done something like this, I guess you should increase the timeouts.

Also, is this live? I can provide more input on taking a closer look.

**Comment by Rishabh570** [comment]
@rexagod Yes, so it returns a promise ( there are promises for every async process ).

Yeah, my changes are live at http://rishabh570.me/community-toolbox/

**Comment by rexagod** [comment]
Hey @Rishabh570, sorry I got a little busy over at ldi and forgot about this. Taking a look now!

**Comment by rexagod** [comment]
@Rishabh570 I guess you should try resolving the promise before passing it down the chain, like this,
```
return fetch(`https://api.github.com/repos/${org}/${repo}/commits?since=${queryTime}`)
// add this =========              
  .then(function(res) {
                  if(response.status === "200") {
                    return Promise.resolve(res);
                  }
                })
// ===============
                .then(function gotResponse(response) {
                        return response.json();
                })
```
Let me know if this fixes it!

**Comment by Rishabh570** [comment]
@rexagod @jywarren Please visit http://rishabh570.me/community-toolbox/ . Now it's working fine...Here's the GIF,

REFACTOR_FINAL


[ I re-pushed it to my `gh-pages` ]

**Comment by Rishabh570** [comment]
Done with some final little changes regarding the recent contribs utility file name change...It's ready now I think...

**Comment by jywarren** [comment]
Yes it works well! And it's fast! I'll merge this now, great work! Would you like merge rights to `publiclab gh-pages` or do you have that already?

**Comment by Rishabh570** [comment]
@jywarren No, I don't have those rights to PL's `gh-pages` currently...

**Comment by jywarren** [comment]
Are you sure? I think you have write permissions for the project.

**Comment by Rishabh570** [comment]
I was a little confused actually...am I supposed to update publiclab/community-toolbox's `gh-pages`?

**Comment by jywarren** [comment]
If you're comfortable doing so, please do! It is a merge commit because the
node modules have been added to that branch.

**Comment by Rishabh570** [comment]
I've never done it before but I would love to try that...
So basically PL's main will be merged with gh-pages and gh-pages will have
a mere commit, right?

**Comment by jywarren** [comment]
Yes, that's right!

**Pull request merged**
