### PR TITLE
Add tests for utils folder

### PR DESCRIPTION
**Pull request by Rishabh570**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Rishabh570** [comment]
@jywarren @publiclab/reviewers I've added unit tests for `/utils/` code (for about 60% of the code)...please take a look. Is it good or I need to structure it differently?

Also, I'll be adding tests for the rest of the code every 1-2 days so that it stays review-able and not get crowded altogether.

Thanks!!!

**Comment by Rishabh570** [comment]
Hi @jywarren, so the tests are ready, here's how the structure looks for `spec/`,

tests_structure

All the tests are passing,

tests_status

So with this PR, tests cover all the code `utils/` (controller layer) folder. Please take a look, is it good to go?

**Comment by jywarren** [comment]
Wow, this is very impressive, and the readout is really nice. This sounds
great. Did you want to do TravisCI integration too?

**Comment by Rishabh570** [comment]
I removed version 6 of the node from `travis.yml` file because a package (`jest-when`) was not working fine in that version because of some _spread operator_ issue...other than that, I guess tests are running fine on Travis too.

**Comment by jywarren** [comment]
Oh awesome, didn't see as i was responding by email :-)

image

This looks awesome! Let's merge it!

**Pull request merged**
