### PR TITLE
Designing view of recent contributor list

### LINKED ISSUE #150: Changing Contributors List UI To Bootstrap Card
### Please describe the problem (or idea)

Currently view or the way website presents the list of contributors is very
Instead of that we can use bootstrap card for good view or desiging the lists of contributors

### PR DESCRIPTION
**Pull request by subhahu123**
Fixes #150

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

## before
screenshot-code publiclab org-2019 03 03-03-59-54

## after
screenshot-127 0 0 1-5500-2019 03 03-03-02-04

### CODE REVIEW

**Comment by gauravano** [comment]
Hey @subhahu123, please add the issue number in the PR or the description. Thanks!

**Comment by subhahu123** [comment]
@gauravano done

**Comment by Rishabh570** [comment]
Hi @subhahu123, a small chat about card UI was held [here](https://github.com/publiclab/community-toolbox/issues/127)...you can take a look there (you can discuss there also) to finalize how to design it :)

**Comment by subhahu123** [comment]
@jywarren please review and merge this

**Comment by jywarren** [comment]
Hi @subhahu123 ! Thank you for your help! I [wrote back to your other PR](https://github.com/publiclab/community-toolbox/pull/145) as well about something similar - and I think @Rishabh570 is right that we should talk through some of these design issues first to be sure we don't miss anything. Thank you!!

**Comment by subhahu123** [comment]
@jywarren  i tried testing with tape
There was problem with fetch and local storage ( can be more ) because they are not still implemented in the node js . we have to test them using libraries called ( node-fetch , node-localstorage )
also test do not support the ES6 ( like aero function )

I think we should not use tape for testing 
we can use other testing library (  like mocha, jasmine or any )
what do u think what we should use ????

And I think we use framework for mvc ( like ember or handlebars  for simplicity ) which includes templating engine better for our architecture so that we can implement more feature like filters ( for getting FTO issue according to beginners known language or their interest ) 

we should not load whole big contributors list in one time . i mean we can divide it into pagination or something like `show  more` button
and can some beginner live (small ) project in bottom , so that they can play with them ( on website itself ) something like  
i  m working on my GSOC proposal So, what do u think we should use and about feature mentioned above

**Pull request closed without merging**
