### PR TITLE
Sticky footer to clear the database which updates it along with the cache (with a page reload). Shows requests left also.

### PR DESCRIPTION
**Pull request by Rishabh570**
This is how I'm imagining the functionality of this feature (Shown in GIF),

clearDBfinal

In this GIF I've only enabled stale issues' list that's why the database has only that after reload. Also, as you can see "request-left" counter is showing real-time info.

A couple of things,
- The "Update Now" button will be disabled if requests left are less than 60. [Todo]
- This footer would be of less opacity when the page is being scrolled up. [Todo]
- While reloading, the footer is blank...some text like "Analyzing..." would be appropriate I think. :thinking: 

@jywarren Please take a look. Work is not completed yet, It's just one way of implementing it. What do you think?

### CODE REVIEW

**Comment by jywarren** [comment]
Oh, this is really nice! Maybe we make it possible to dismiss? And, can we
use standard Bootstrap alerts? Thank you!!!

**Comment by Rishabh570** [comment]
A bootstrap alert would totally make sense...so when will the dismissed footer show up, I mean, what if the footer fades out when not in focus? If we totally allow dismissing the footer, what makes it pop up again...maybe show footer only when we can actually click "Update Now"/ requests are full?

Thanks!

**Comment by jywarren** [comment]
Sure! Or we could minimize it into a small corner button or something, if
you think there'll be a need to get it back?

**Comment by Rishabh570** [comment]
People need to know when they can refresh the DB when they click the button, so what if we only show the "Update Now" button and when people click it, an alert will pop up showing the info we're currently showing in the footer. So, there'll be 2 cases when people click the button:
1. Alert will show the time remaining (info that is currently in the footer),
2. Alert for the successful operation.

@jywarren This way we'll not be blocking any content...Also, is there a need for the request counter, as we're showing cooldown time anyways?

**Comment by Rishabh570** [comment]
In this approach, we're not blocking any content and still conveying the necessary information. Please take a look,

refresh-spinner-button

(Btw, we can also use the snack bar here instead of alert...)

**Comment by Rishabh570** [comment]
Hi @jywarren, I've changed the refresh button UI & placement. Which one do you think would be more user-friendly?

Thanks!

**Comment by jywarren** [comment]
Oh! I like this last screenshot, really nicely done!

**Comment by Rishabh570** [comment]
Hi @jywarren, is this good to go or we need some modifications?
I needed to force push after rebasing after resolving some minor conflicts, please take a look.

**Comment by Rishabh570** [comment]
Also, used snackbar for notification. Here's the latest GIF,
refresh-button

**Comment by jywarren** [comment]
Oh no, i'm sorry @Rishabh570 this looks really good. If you'd like to rebase one more time we can go ahead and merge. My sincere apologies for not replying and I hope you are well.

**Comment by Rishabh570** [comment]
Hi @jywarren :wave: 

Oops, don't know how this slipped by. Seems like there are some conflicts here; I'll try to push this fresh sometime this coming weekend.

Thanks, I hope you're doing great as well!!!

**Comment by jywarren** [comment]
Oh thank you so much and I hope you're well too!

**Comment by jywarren** [comment]
Fantastic, thank you!!!

**Pull request merged**
